services:
  php:
    container_name: apache_php_xdebug
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./app:/var/www/app
    ports:
      - 8080:80
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_CONFIG: "idekey=apache_php_xdebug"
      ENABLE_XDEBUG: "1"
