services:
  php:
    container_name: apache_php
    image: alaugks/apache-php:local
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - ./app:/var/www/app
    ports:
      - "8080:80"
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_CONFIG: "idekey=apache_php_xdebug"
