services:
  php:
    container_name: xdebug_test
    image: local/apache-php-mod-xdebug:8.2.21-v1.0
    volumes:
      - ./app:/var/www/app
    ports:
      - 8080:80
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_CONFIG: "idekey=xdebug_test"
