name: Push Image
run-name: Push Image [${{github.ref_name}}]
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: alaugks/apache-php:${{github.ref_name}}
      IMAGE_NAME_XDEBUG: alaugks/apache-php:${{github.ref_name}}-xdebug

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push (with XDebug)
        uses: docker/build-push-action@v6.4.1
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENABLE_XDEBUG=1
          push: false
          load: true
          tags: ${{env.IMAGE_NAME_XDEBUG}}

      - name: Test run image (with XDebug)
        run: |
          docker run \
            -p 8080:80 \
            --rm ${{env.IMAGE_NAME_XDEBUG}}

      - name: Build and push (with XDebug)
        uses: docker/build-push-action@v6.4.1
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENABLE_XDEBUG=1
          push: true
          tags: ${{env.IMAGE_NAME_XDEBUG}}

      - name: Build and push
        uses: docker/build-push-action@v6.4.1
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{env.IMAGE_NAME}}
