name: Push Image
run-name: Push Image [${{github.ref_name}}]
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./
          load-mode: strict

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

#      - name: Build-Test (with XDebug)
#        uses: docker/build-push-action@v4.2.1
#        with:
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#          context: .
#          file: Dockerfile
#          platforms: linux/amd64,linux/arm64
#          build-args: |
#            ENABLE_XDEBUG=yes
#          load: true
#          tags: alaugks/apache-php:${{github.ref_name}}-xdebug
#
#      - name: Test run image (with XDebug)
#        run: |
#          docker run \
#            -p 8080:80 \
#            --rm alaugks/apache-php:${{github.ref_name}}-xdebug

      - name: Build and push (with XDebug)
        uses: docker/build-push-action@v4.2.1
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENABLE_XDEBUG=yes
          push: true
          tags: alaugks/apache-php:${{github.ref_name}}-xdebug

      - name: Build and push
        uses: docker/build-push-action@v4.2.1
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: alaugks/apache-php:${{github.ref_name}}
