name: Push Image
run-name: Push Image [${{github.ref_name}}]
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      #      - name: Environment Tasks
      #        run: |
      #          # Deployment only with tag is "prod"
      #          if [[ ! '${{github.ref_type}}' == 'tag' ]]; then
      #              echo "No Tag selected"
      #          fi

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          load: true
          tags: ${{env.DOCKER_IMAGE}}:${{env.VERSION}}-${{github.ref_name}}-${{env.TEST_TAG}}

      - name: Test
        run: |
          docker run \
            -p 8080:80 \
            --rm ${{env.DOCKER_IMAGE}}:${{env.VERSION}}-${{github.ref_name}}-${{env.TEST_TAG}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{env.DOCKER_IMAGE}}:${{env.VERSION}}-${{github.ref_name}}
