name: Push Image
run-name: Push Image [${{github.ref_name}}]
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Image and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./
          load-mode: strict

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and Push Image
        run: |
          docker buildx create --use
          docker buildx build \
            --file Dockerfile \
            --build-arg VERSION=${{env.VERSION}} \
            --platform linux/amd64,linux/arm64 \
            --tag ${{env.DOCKER_IMAGE}}:${{env.VERSION}}-${{env.SUB_TAG}} \
            --push .
